### ISSUE TITLE
Инфологическая схема данных

### ISSUE THREAD

**Issue by Warh40k** [Warh40k/shareat#2]
Описать основные сущности, поля без привязки к конкретной СУБД. 
Нотацию выбрать на свой вкус и цвет
Загрузить в отдельную ветку репы в каталог с именем `spec` саму схему + приложить файл здесь в комментах

**Comment by Haderdsins** [comment]
https://dbdesign.online/model/9qdxK8FT5bQn
![Uploading Diagram_27_09_2024_19_53.png…]()

**Comment by Haderdsins** [comment]
https://dbdesign.online/model/9qdxK8FT5bQn
![Diagram_27_09_2024_19_53](https://github.com/user-attachments/assets/6d139cf5-f1e7-47c4-b1d9-a1b7461398c9)
